apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::297894163141:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-f9V9XTNqlI5t
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::297894163141:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2024-05-19T06:11:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1416"
  uid: 74eeb607-6ddf-4bfb-b2bc-097a07ad6811
